# Generated by Django 2.2.5 on 2019-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(default='Name', max_length=30)),
                ('feedback_email', models.CharField(default='E-mail', max_length=30)),
                ('feedback', models.TextField(default='Feedback', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'feedback',
            },
        ),
    ]
