# Generated by Django 2.2.5 on 2019-09-21 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190921_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='about_us',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
