# Generated by Django 2.2.5 on 2019-09-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(default='Name', max_length=30)),
                ('feedback_email', models.CharField(default='E-mail', max_length=30)),
                ('feedback', models.TextField(default='Feedback', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='review/')),
                ('name', models.CharField(default='name', max_length=30)),
                ('customer', models.CharField(default='Satisfied Customer', max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('title', models.CharField(default='title', max_length=30)),
                ('description', models.TextField(default='description', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
    ]
